import WebPush from 'web-push'
import { FastifyInstance } from 'fastify'

// const publicKey = 'PUBLIC KEY GENERATED BY WebPush.generateVAPIDKeys()'
// const privateKey = 'PRIVATE KEY GENERATED BY WebPush.generateVAPIDKeys()'


const publicKey = 'BJ08IxaLaN8s8a_RDe5g4L_8GFjEX6pAUbL_JC4V4DJw4h8-9MNByeXoSKfxvN1_M6oYaj-kITK634OxfV5Xo-I'
const privateKey = 'bmG9tmDAto1O25o4PVABy4f9Gz1r8fppx_6In7dJBjI'

WebPush.setVapidDetails('http://localhost:3333', publicKey, privateKey)

export async function notificationRoutes(app: FastifyInstance){
  app.get('/push/public_key', () => {
    return {
      publicKey,
    }
  })

  app.post('/push/register', (request, reply) => {
    console.log(request.body)

    return reply.status(201).send()
  })

  app.post('/push/send', async (request, reply) => {
    console.log(request.body)

    return reply.status(201).send()
  })
}
