import WebPush from 'web-push'
import { FastifyInstance } from 'fastify'

const publicKey = 'PUBLIC KEY GENERATED BY WebPush.generateVAPIDKeys()'
const privateKey = 'PRIVATE KEY GENERATED BY WebPush.generateVAPIDKeys()'

export async function notificationRoutes(app: FastifyInstance){
  
}
