import WebPush from 'web-push'
import { FastifyInstance } from 'fastify'

// const publicKey = 'PUBLIC KEY GENERATED BY WebPush.generateVAPIDKeys()'
// const privateKey = 'PRIVATE KEY GENERATED BY WebPush.generateVAPIDKeys()'

//WebPush.setVapidDetails('http://localhost:3333', publicKey, privateKey)

export async function notificationRoutes(app: FastifyInstance){
  app.get('/push/public_key', () => {
    return {
      // publicKey,
    }
  })

  app.post('/push/register', (request, reply) => {
    console.log(request.body)

    return reply.status(201).send()
  })

  app.post('/push/send', async (request, reply) => {
    console.log(request.body)

    return reply.status(201).send()
  })
}
